// =====================================================
// Sankampaeng Hospital - Discharge Center Mock Data
// ระบบจัดการข้อมูล Discharge Center โรงพยาบาลสันกำแพง
// =====================================================

const MOCK_DATA = {

  // ==================== DASHBOARD ====================
  dashboard: {
    totalInpatients: 47,
    pendingDischarge: 8,
    todayDischarge: 3,
    dischargedThisMonth: 42,
    followUpDueToday: 5,
    followUpOverdue: 2,
    readmissionRate: 4.2,
    avgLOS: 4.8,
    bedOccupancy: 78.5,
    totalBeds: 60,
    occupiedBeds: 47,

    wardSummary: [
      { name: 'อายุรกรรมชาย', beds: 12, occupied: 10, pending: 2 },
      { name: 'อายุรกรรมหญิง', beds: 12, occupied: 9, pending: 1 },
      { name: 'ศัลยกรรม', beds: 10, occupied: 8, pending: 2 },
      { name: 'สูติ-นรีเวช', beds: 8, occupied: 6, pending: 1 },
      { name: 'กุมารเวชกรรม', beds: 8, occupied: 7, pending: 1 },
      { name: 'CCU/ICU', beds: 6, occupied: 5, pending: 1 },
      { name: 'พิเศษ', beds: 4, occupied: 2, pending: 0 },
    ],

    dischargeByMonth: [
      { month: 'ก.ย.', count: 38 },
      { month: 'ต.ค.', count: 41 },
      { month: 'พ.ย.', count: 35 },
      { month: 'ธ.ค.', count: 44 },
      { month: 'ม.ค.', count: 39 },
      { month: 'ก.พ.', count: 42 },
    ],

    readmissionByMonth: [
      { month: 'ก.ย.', count: 2 },
      { month: 'ต.ค.', count: 1 },
      { month: 'พ.ย.', count: 3 },
      { month: 'ธ.ค.', count: 2 },
      { month: 'ม.ค.', count: 1 },
      { month: 'ก.พ.', count: 2 },
    ],

    topDiagnosis: [
      { name: 'DM with complications', count: 12 },
      { name: 'COPD exacerbation', count: 8 },
      { name: 'Pneumonia', count: 7 },
      { name: 'CHF', count: 6 },
      { name: 'Stroke', count: 5 },
    ],

    recentActivities: [
      { time: '10:30', action: 'จำหน่ายผู้ป่วย', patient: 'นายวิชัย มั่นคง', detail: 'AN: 67-001220 Ward: ศัลยกรรม', type: 'discharge' },
      { time: '09:45', action: 'วางแผนจำหน่าย', patient: 'นางสมหญิง รักสุข', detail: 'Stroke - เริ่มวางแผน D-METHOD', type: 'plan' },
      { time: '09:15', action: 'โทรติดตามผล', patient: 'นายทองดี เจริญผล', detail: '48 ชม. หลังจำหน่าย - สถานะดี', type: 'followup' },
      { time: '08:30', action: 'เยี่ยมบ้าน', patient: 'นางบุญมี ศรีสุข', detail: 'เยี่ยมบ้านครั้งที่ 1 - Hip fracture', type: 'homevisit' },
      { time: '08:00', action: 'รับผู้ป่วยใหม่', patient: 'นายประสิทธิ์ ลือชา', detail: 'AN: 67-001250 Ward: อายุรกรรมชาย', type: 'admit' },
    ],

    pendingTasks: [
      { type: 'urgent', text: 'โทรติดตามผล 48 ชม. - นางวิไล ชูศรี (เลยกำหนด 1 วัน)', patient: 'นางวิไล ชูศรี' },
      { type: 'urgent', text: 'เตรียมอุปกรณ์ดูดเสมหะ - นายสุรชัย แก้วใส (จำหน่ายวันนี้)', patient: 'นายสุรชัย แก้วใส' },
      { type: 'warning', text: 'วางแผนจำหน่ายยังไม่ครบ - นางสมหญิง รักสุข (D-METHOD 4/7)', patient: 'นางสมหญิง รักสุข' },
      { type: 'warning', text: 'นัดเยี่ยมบ้าน - นายประเสริฐ มั่นคง (พรุ่งนี้)', patient: 'นายประเสริฐ มั่นคง' },
      { type: 'info', text: 'ประชุม Discharge Planning Team ประจำสัปดาห์ (14:00 น.)', patient: null },
    ],
  },

  // ==================== CURRENT INPATIENTS ====================
  patients: [
    {
      id: 'P001',
      hn: '64-012345',
      an: '67-001234',
      name: 'นายสมชาย ใจดี',
      gender: 'male',
      age: 65,
      idCard: '5-5001-00123-45-6',
      phone: '081-234-5678',
      address: '123 หมู่ 5 ต.สันกำแพง อ.สันกำแพง จ.เชียงใหม่ 50130',
      ward: 'อายุรกรรมชาย',
      bed: '3A-12',
      room: '3A',
      admitDate: '2026-02-26',
      diagnosis: 'DM type 2 with Diabetic foot, HT',
      diagnosisICD: 'E11.6, I10',
      attendingDoc: 'นพ.วิชัย สุขสันต์',
      admitFrom: 'OPD',
      insurance: 'บัตรทอง',
      allergies: 'Penicillin',
      dischargeStatus: 'planning',
      riskLevel: 'high',
      los: 6,
      expectedDischargeDate: '2026-03-06',
      bmi: 28.5,
      bloodType: 'O',
      caregiver: {
        name: 'นางสมศรี ใจดี',
        relation: 'ภรรยา',
        phone: '089-876-5432',
        canCare: true,
      },
      dischargePlan: {
        status: 'in_progress',
        completedItems: 5,
        totalItems: 7,
        dMethod: {
          disease: { status: 'completed', note: 'ผู้ป่วยเข้าใจโรคเบาหวานและความดันโลหิตสูง สามารถบอกอาการผิดปกติได้' },
          medication: { status: 'completed', note: 'ฉีดอินซูลิน Mixtard 30 ได้ด้วยตนเอง, ยา Amlodipine 5mg OD, Metformin 500mg BID' },
          environment: { status: 'completed', note: 'บ้านชั้นเดียว ห้องน้ำมีราวจับ ไม่มีสัตว์เลี้ยง' },
          treatment: { status: 'completed', note: 'ทำแผล Diabetic foot วันละ 1 ครั้ง, วัด BS ก่อนอาหารเช้า-เย็น' },
          health: { status: 'completed', note: 'สอนการดูแลเท้า, การออกกำลังกาย, การสังเกตอาการน้ำตาลต่ำ/สูง' },
          outpatient: { status: 'pending', note: 'รอนัด OPD อายุรกรรม 2 สัปดาห์, นัดทำแผล 3 วัน' },
          diet: { status: 'pending', note: 'รอนักโภชนาการให้คำแนะนำอาหาร DM + HT' },
        },
        medications: [
          { name: 'Insulin Mixtard 30', dose: '20 units เช้า, 10 units เย็น', route: 'SC', frequency: 'BID', note: 'ก่อนอาหาร 30 นาที' },
          { name: 'Metformin 500mg', dose: '1 เม็ด', route: 'PO', frequency: 'BID', note: 'หลังอาหาร' },
          { name: 'Amlodipine 5mg', dose: '1 เม็ด', route: 'PO', frequency: 'OD', note: 'เช้า' },
          { name: 'Aspirin 81mg', dose: '1 เม็ด', route: 'PO', frequency: 'OD', note: 'หลังอาหารเช้า' },
        ],
        equipment: ['ชุดตรวจน้ำตาลในเลือด (Glucometer)', 'เข็มฉีดอินซูลิน', 'ชุดทำแผล'],
        specialInstructions: [
          'วัดน้ำตาลในเลือดก่อนอาหารเช้าและเย็นทุกวัน บันทึกผล',
          'ทำแผลที่เท้าขวาวันละ 1 ครั้ง ด้วย Normal saline + Betadine',
          'งดรับประทานของหวาน ผลไม้หวานจัด อาหารเค็ม',
          'สวมรองเท้าหุ้มส้นเสมอ ห้ามเดินเท้าเปล่า',
          'ถ้ามีอาการใจสั่น เหงื่อออก มือสั่น ให้ดื่มน้ำหวาน 1 แก้ว แล้วมาพบแพทย์',
        ],
      },
    },
    {
      id: 'P002',
      hn: '63-009876',
      an: '67-001235',
      name: 'นางสมหญิง รักสุข',
      gender: 'female',
      age: 58,
      idCard: '5-5001-00234-56-7',
      phone: '082-345-6789',
      address: '45/2 หมู่ 3 ต.แช่ช้าง อ.สันกำแพง จ.เชียงใหม่ 50130',
      ward: 'อายุรกรรมหญิง',
      bed: '2B-05',
      room: '2B',
      admitDate: '2026-02-28',
      diagnosis: 'Ischemic Stroke, Left hemiparesis',
      diagnosisICD: 'I63.9',
      attendingDoc: 'นพ.สมบูรณ์ เวชการ',
      admitFrom: 'ER',
      insurance: 'ประกันสังคม',
      allergies: 'ไม่มี',
      dischargeStatus: 'planning',
      riskLevel: 'high',
      los: 4,
      expectedDischargeDate: '2026-03-08',
      bmi: 26.2,
      bloodType: 'A',
      caregiver: {
        name: 'นายสมศักดิ์ รักสุข',
        relation: 'สามี',
        phone: '083-456-7890',
        canCare: true,
      },
      dischargePlan: {
        status: 'in_progress',
        completedItems: 4,
        totalItems: 7,
        dMethod: {
          disease: { status: 'completed', note: 'ผู้ป่วยและญาติเข้าใจโรคหลอดเลือดสมอง ปัจจัยเสี่ยง และอาการเตือน' },
          medication: { status: 'completed', note: 'ยา Aspirin 325mg OD, Atorvastatin 40mg OD, Amlodipine 10mg OD' },
          environment: { status: 'pending', note: 'รอประเมินสภาพบ้าน - บ้าน 2 ชั้น อาจต้องปรับปรุง' },
          treatment: { status: 'completed', note: 'ทำกายภาพบำบัดต่อ, กิจกรรมบำบัด, ฝึก ADL' },
          health: { status: 'completed', note: 'สอนการป้องกันการล้ม, การฝึกกล้ามเนื้อ, FAST assessment' },
          outpatient: { status: 'pending', note: 'รอนัด OPD อายุรกรรม + กายภาพบำบัด' },
          diet: { status: 'pending', note: 'กลืนลำบาก - รอ Swallowing assessment' },
        },
        medications: [
          { name: 'Aspirin 325mg', dose: '1 เม็ด', route: 'PO', frequency: 'OD', note: 'หลังอาหารเช้า' },
          { name: 'Atorvastatin 40mg', dose: '1 เม็ด', route: 'PO', frequency: 'OD', note: 'ก่อนนอน' },
          { name: 'Amlodipine 10mg', dose: '1 เม็ด', route: 'PO', frequency: 'OD', note: 'เช้า' },
          { name: 'Clopidogrel 75mg', dose: '1 เม็ด', route: 'PO', frequency: 'OD', note: 'เช้า' },
        ],
        equipment: ['Walker / ไม้เท้า 4 ขา', 'ราวจับติดผนัง', 'เก้าอี้นั่งอาบน้ำ'],
        specialInstructions: [
          'ทำกายภาพบำบัดตามโปรแกรมที่กำหนดทุกวัน',
          'ระวังการล้ม ใช้ Walker เวลาเดิน',
          'วัดความดันโลหิตวันละ 2 ครั้ง เช้า-เย็น',
          'ถ้ามีอาการ FAST (Face drooping, Arm weakness, Speech difficulty, Time to call) ให้โทร 1669 ทันที',
          'งดสูบบุหรี่ งดเครื่องดื่มแอลกอฮอล์',
        ],
      },
    },
    {
      id: 'P003',
      hn: '65-003456',
      an: '67-001230',
      name: 'นายประเสริฐ มั่นคง',
      gender: 'male',
      age: 72,
      idCard: '5-5001-00345-67-8',
      phone: '084-567-8901',
      address: '78 หมู่ 8 ต.ออนใต้ อ.สันกำแพง จ.เชียงใหม่ 50130',
      ward: 'อายุรกรรมชาย',
      bed: '3A-08',
      room: '3A',
      admitDate: '2026-02-24',
      diagnosis: 'COPD Acute Exacerbation',
      diagnosisICD: 'J44.1',
      attendingDoc: 'นพ.วิชัย สุขสันต์',
      admitFrom: 'ER',
      insurance: 'บัตรทอง',
      allergies: 'Sulfa drugs',
      dischargeStatus: 'ready',
      riskLevel: 'medium',
      los: 8,
      expectedDischargeDate: '2026-03-04',
      bmi: 20.1,
      bloodType: 'B',
      caregiver: {
        name: 'นางสายใจ มั่นคง',
        relation: 'ภรรยา',
        phone: '085-678-9012',
        canCare: true,
      },
      dischargePlan: {
        status: 'completed',
        completedItems: 7,
        totalItems: 7,
        dMethod: {
          disease: { status: 'completed', note: 'ผู้ป่วยเข้าใจ COPD และอาการกำเริบ หลีกเลี่ยงสิ่งกระตุ้น' },
          medication: { status: 'completed', note: 'Inhaler technique ถูกต้อง, ยาพ่น Seretide 250/50, Ventolin MDI PRN' },
          environment: { status: 'completed', note: 'บ้านชั้นเดียว อากาศถ่ายเทดี ไม่มีควันบุหรี่' },
          treatment: { status: 'completed', note: 'Breathing exercise, Pursed lip breathing' },
          health: { status: 'completed', note: 'สอนการใช้ยาพ่น การหายใจ การสังเกตอาการ' },
          outpatient: { status: 'completed', note: 'นัด OPD อายุรกรรม 7 มี.ค. 69 เวลา 09:00 น.' },
          diet: { status: 'completed', note: 'อาหารพลังงานสูง โปรตีนสูง แบ่งมื้อย่อย' },
        },
        medications: [
          { name: 'Seretide 250/50 MDI', dose: '2 puffs', route: 'INH', frequency: 'BID', note: 'เช้า-เย็น บ้วนปากหลังพ่น' },
          { name: 'Ventolin MDI', dose: '2 puffs', route: 'INH', frequency: 'PRN', note: 'เมื่อหอบ (ไม่เกิน 4 ครั้ง/วัน)' },
          { name: 'Prednisolone 5mg', dose: '2 เม็ด', route: 'PO', frequency: 'OD', note: 'เช้า x 5 วัน แล้วหยุด' },
          { name: 'Theophylline 200mg', dose: '1 เม็ด', route: 'PO', frequency: 'BID', note: 'เช้า-เย็น' },
        ],
        equipment: ['Spacer สำหรับยาพ่น', 'เครื่องวัด Peak Flow'],
        specialInstructions: [
          'หลีกเลี่ยงควัน ฝุ่น อากาศเย็น สารระคายเคือง',
          'ทำ Breathing exercise วันละ 3 ครั้ง ครั้งละ 10 นาที',
          'วัด Peak Flow ทุกเช้า บันทึกผล',
          'ถ้า Peak Flow < 200 หรือ หอบมาก ให้มาพบแพทย์ทันที',
          'งดสูบบุหรี่โดยเด็ดขาด',
        ],
      },
    },
    {
      id: 'P004',
      hn: '66-007890',
      an: '67-001240',
      name: 'เด็กชายภูมิ สดใส',
      gender: 'male',
      age: 5,
      idCard: '5-5001-00456-78-9',
      phone: '086-789-0123',
      address: '56 หมู่ 2 ต.สันกำแพง อ.สันกำแพง จ.เชียงใหม่ 50130',
      ward: 'กุมารเวชกรรม',
      bed: '5-03',
      room: '5',
      admitDate: '2026-03-01',
      diagnosis: 'Pneumonia',
      diagnosisICD: 'J18.9',
      attendingDoc: 'พญ.นิภา เด็กดี',
      admitFrom: 'OPD',
      insurance: 'บัตรทอง',
      allergies: 'ไม่มี',
      dischargeStatus: 'planning',
      riskLevel: 'low',
      los: 3,
      expectedDischargeDate: '2026-03-05',
      bmi: 15.2,
      bloodType: 'AB',
      caregiver: {
        name: 'นางนภา สดใส',
        relation: 'มารดา',
        phone: '086-789-0123',
        canCare: true,
      },
      dischargePlan: {
        status: 'in_progress',
        completedItems: 3,
        totalItems: 7,
        dMethod: {
          disease: { status: 'completed', note: 'มารดาเข้าใจโรคปอดอักเสบ อาการที่ต้องเฝ้าระวัง' },
          medication: { status: 'completed', note: 'ยา Amoxicillin syrup ให้ครบ 7 วัน' },
          environment: { status: 'completed', note: 'บ้านสะอาด อากาศถ่ายเทดี' },
          treatment: { status: 'pending', note: 'รอผล CXR ก่อนจำหน่าย' },
          health: { status: 'pending', note: 'รอสอนมารดาเรื่องการดูดเสมหะ การเคาะปอด' },
          outpatient: { status: 'pending', note: 'นัด OPD กุมาร 1 สัปดาห์' },
          diet: { status: 'pending', note: 'อาหารตามวัย เสริมโปรตีน' },
        },
        medications: [
          { name: 'Amoxicillin syrup 250mg/5ml', dose: '5 ml', route: 'PO', frequency: 'TID', note: 'หลังอาหาร x 7 วัน' },
          { name: 'Paracetamol syrup 120mg/5ml', dose: '5 ml', route: 'PO', frequency: 'PRN', note: 'เมื่อมีไข้ > 38.5°C' },
          { name: 'Bromhexine syrup', dose: '2.5 ml', route: 'PO', frequency: 'TID', note: 'หลังอาหาร' },
        ],
        equipment: [],
        specialInstructions: [
          'ให้ยาปฏิชีวนะจนครบ 7 วัน ห้ามหยุดยาเอง',
          'วัดไข้ทุก 4-6 ชั่วโมง',
          'ดื่มน้ำมากๆ พักผ่อนให้เพียงพอ',
          'ถ้าไข้สูง > 39°C หรือหายใจเร็วมาก ให้มาพบแพทย์ทันที',
        ],
      },
    },
    {
      id: 'P005',
      hn: '62-005432',
      an: '67-001225',
      name: 'นางวิไล ชูศรี',
      gender: 'female',
      age: 70,
      idCard: '5-5001-00567-89-0',
      phone: '087-890-1234',
      address: '89/1 หมู่ 6 ต.บวกค้าง อ.สันกำแพง จ.เชียงใหม่ 50130',
      ward: 'อายุรกรรมหญิง',
      bed: '2B-10',
      room: '2B',
      admitDate: '2026-02-22',
      diagnosis: 'CHF NYHA III, AF',
      diagnosisICD: 'I50.9, I48',
      attendingDoc: 'นพ.สมบูรณ์ เวชการ',
      admitFrom: 'ER',
      insurance: 'บัตรทอง',
      allergies: 'ACE inhibitors (ไอ)',
      dischargeStatus: 'ready',
      riskLevel: 'high',
      los: 10,
      expectedDischargeDate: '2026-03-04',
      bmi: 24.8,
      bloodType: 'O',
      caregiver: {
        name: 'นางสาวสุดา ชูศรี',
        relation: 'บุตรสาว',
        phone: '088-901-2345',
        canCare: true,
      },
      dischargePlan: {
        status: 'completed',
        completedItems: 7,
        totalItems: 7,
        dMethod: {
          disease: { status: 'completed', note: 'เข้าใจโรคหัวใจล้มเหลว อาการที่ต้องเฝ้าระวัง น้ำหนักเพิ่ม บวม หอบ' },
          medication: { status: 'completed', note: 'ยา 5 ชนิด เข้าใจวิธีรับประทานถูกต้อง' },
          environment: { status: 'completed', note: 'บ้านชั้นเดียว สะดวกในการดูแล' },
          treatment: { status: 'completed', note: 'ชั่งน้ำหนักทุกเช้า จำกัดน้ำ 1500 ml/วัน' },
          health: { status: 'completed', note: 'สอนการจำกัดเกลือ น้ำ การออกกำลังกายเบาๆ' },
          outpatient: { status: 'completed', note: 'นัด OPD อายุรกรรม 11 มี.ค. 69 เวลา 10:00 น.' },
          diet: { status: 'completed', note: 'อาหารจืด จำกัดเกลือ < 2g/วัน จำกัดน้ำ' },
        },
        medications: [
          { name: 'Furosemide 40mg', dose: '1 เม็ด', route: 'PO', frequency: 'OD', note: 'เช้า' },
          { name: 'Spironolactone 25mg', dose: '1 เม็ด', route: 'PO', frequency: 'OD', note: 'เช้า' },
          { name: 'Carvedilol 6.25mg', dose: '1 เม็ด', route: 'PO', frequency: 'BID', note: 'เช้า-เย็น หลังอาหาร' },
          { name: 'Digoxin 0.125mg', dose: '1 เม็ด', route: 'PO', frequency: 'OD', note: 'เช้า (จ-ศ หยุด ส-อา)' },
          { name: 'Warfarin 3mg', dose: '1 เม็ด', route: 'PO', frequency: 'OD', note: 'หลังอาหารเย็น ตรวจ INR ตามนัด' },
        ],
        equipment: ['เครื่องชั่งน้ำหนัก', 'เครื่องวัดความดันโลหิต'],
        specialInstructions: [
          'ชั่งน้ำหนักทุกเช้า ถ้าน้ำหนักเพิ่ม > 1 กก./วัน หรือ > 2 กก./สัปดาห์ ให้มาพบแพทย์',
          'จำกัดน้ำดื่ม ไม่เกิน 1500 ml/วัน',
          'อาหารจืด จำกัดเกลือ < 2 กรัม/วัน',
          'รับประทาน Warfarin ตรงเวลา ห้ามซื้อยาเองโดยเด็ดขาด',
          'ตรวจ INR ตามนัด ระวังเลือดออกผิดปกติ',
          'ถ้าหอบเหนื่อยมากขึ้น นอนราบไม่ได้ ขาบวมมากขึ้น ให้มาพบแพทย์ทันที',
        ],
      },
    },
    {
      id: 'P006',
      hn: '65-008765',
      an: '67-001242',
      name: 'นายอำนวย พรมดี',
      gender: 'male',
      age: 45,
      idCard: '5-5001-00678-90-1',
      phone: '089-012-3456',
      address: '200 หมู่ 1 ต.สันกำแพง อ.สันกำแพง จ.เชียงใหม่ 50130',
      ward: 'ศัลยกรรม',
      bed: '4-06',
      room: '4',
      admitDate: '2026-03-02',
      diagnosis: 'Post Appendectomy (Laparoscopic)',
      diagnosisICD: 'K35.8',
      attendingDoc: 'นพ.ศักดิ์ชัย ผ่าตัดเก่ง',
      admitFrom: 'ER',
      insurance: 'ประกันสังคม',
      allergies: 'ไม่มี',
      dischargeStatus: 'ready',
      riskLevel: 'low',
      los: 2,
      expectedDischargeDate: '2026-03-04',
      bmi: 23.5,
      bloodType: 'A',
      caregiver: {
        name: 'นางสมพร พรมดี',
        relation: 'ภรรยา',
        phone: '090-123-4567',
        canCare: true,
      },
      dischargePlan: {
        status: 'completed',
        completedItems: 7,
        totalItems: 7,
        dMethod: {
          disease: { status: 'completed', note: 'เข้าใจการผ่าตัดไส้ติ่ง การดูแลแผล' },
          medication: { status: 'completed', note: 'ยาแก้ปวด Paracetamol, ยาปฏิชีวนะ' },
          environment: { status: 'completed', note: 'บ้านสะดวก ไม่ต้องปรับปรุง' },
          treatment: { status: 'completed', note: 'ดูแลแผลผ่าตัด ตัดไหม 7 วัน' },
          health: { status: 'completed', note: 'สอนดูแลแผล สังเกตอาการติดเชื้อ' },
          outpatient: { status: 'completed', note: 'นัดตัดไหม 9 มี.ค. 69' },
          diet: { status: 'completed', note: 'อาหารอ่อน 2-3 วัน แล้วปกติ' },
        },
        medications: [
          { name: 'Paracetamol 500mg', dose: '2 เม็ด', route: 'PO', frequency: 'PRN', note: 'เมื่อปวด (ทุก 4-6 ชม.)' },
          { name: 'Amoxicillin/Clavulanate 625mg', dose: '1 เม็ด', route: 'PO', frequency: 'TID', note: 'หลังอาหาร x 5 วัน' },
        ],
        equipment: [],
        specialInstructions: [
          'ดูแลแผลให้แห้ง สะอาด ห้ามแกะเกา',
          'งดยกของหนักเกิน 5 กก. 2 สัปดาห์',
          'ถ้าแผลบวม แดง ร้อน มีหนอง มีไข้ ให้มาพบแพทย์',
          'มาตัดไหมตามนัด 9 มี.ค. 69',
        ],
      },
    },
    {
      id: 'P007',
      hn: '64-006543',
      an: '67-001228',
      name: 'นางบุญมี ศรีสุข',
      gender: 'female',
      age: 78,
      idCard: '5-5001-00789-01-2',
      phone: '091-234-5678',
      address: '33 หมู่ 4 ต.ห้วยทราย อ.สันกำแพง จ.เชียงใหม่ 50130',
      ward: 'ศัลยกรรม',
      bed: '4-02',
      room: '4',
      admitDate: '2026-02-23',
      diagnosis: 'Right Hip Fracture - Post ORIF',
      diagnosisICD: 'S72.0',
      attendingDoc: 'นพ.ศักดิ์ชัย ผ่าตัดเก่ง',
      admitFrom: 'ER',
      insurance: 'บัตรทอง',
      allergies: 'NSAIDs (GI bleeding)',
      dischargeStatus: 'planning',
      riskLevel: 'high',
      los: 9,
      expectedDischargeDate: '2026-03-07',
      bmi: 22.0,
      bloodType: 'B',
      caregiver: {
        name: 'นายสมบัติ ศรีสุข',
        relation: 'บุตรชาย',
        phone: '092-345-6789',
        canCare: true,
      },
      dischargePlan: {
        status: 'in_progress',
        completedItems: 4,
        totalItems: 7,
        dMethod: {
          disease: { status: 'completed', note: 'ญาติเข้าใจการผ่าตัดดามกระดูก การดูแลหลังผ่าตัด' },
          medication: { status: 'completed', note: 'ยาแก้ปวด Paracetamol, ยาป้องกันกระดูกพรุน' },
          environment: { status: 'pending', note: 'ต้องปรับปรุงห้องน้ำ ติดราวจับ ใส่แผ่นกันลื่น' },
          treatment: { status: 'completed', note: 'กายภาพบำบัด ฝึกเดินด้วย Walker' },
          health: { status: 'completed', note: 'สอนการป้องกันการล้ม การใช้ Walker การลุกนั่ง' },
          outpatient: { status: 'pending', note: 'รอนัด OPD ออร์โธ + กายภาพ' },
          diet: { status: 'pending', note: 'เสริมแคลเซียม วิตามินดี' },
        },
        medications: [
          { name: 'Paracetamol 500mg', dose: '2 เม็ด', route: 'PO', frequency: 'TID', note: 'หลังอาหาร' },
          { name: 'Calcium carbonate 1000mg', dose: '1 เม็ด', route: 'PO', frequency: 'BID', note: 'หลังอาหาร' },
          { name: 'Vitamin D 20,000 IU', dose: '1 เม็ด', route: 'PO', frequency: 'Weekly', note: 'ทุกวันจันทร์' },
          { name: 'Omeprazole 20mg', dose: '1 เม็ด', route: 'PO', frequency: 'OD', note: 'ก่อนอาหารเช้า 30 นาที' },
        ],
        equipment: ['Walker', 'ราวจับติดผนังห้องน้ำ', 'เบาะรองนั่ง', 'แผ่นกันลื่น'],
        specialInstructions: [
          'ใช้ Walker เดินเสมอ ห้ามเดินโดยไม่มีอุปกรณ์ช่วย',
          'ห้ามนั่งยองๆ ห้ามนั่งพับเพียบ ห้ามนั่งขัดสมาธิ',
          'ทำกายภาพบำบัดตามโปรแกรม',
          'ระวังการล้ม เปิดไฟให้สว่าง ติดราวจับในห้องน้ำ',
          'ถ้าขาบวมมาก ปวดมาก แผลมีหนอง ให้มาพบแพทย์',
        ],
      },
    },
    {
      id: 'P008',
      hn: '66-001234',
      an: '67-001245',
      name: 'นายสุรชัย แก้วใส',
      gender: 'male',
      age: 60,
      idCard: '5-5001-00890-12-3',
      phone: '093-456-7890',
      address: '15 หมู่ 9 ต.ร้องวัวแดง อ.สันกำแพง จ.เชียงใหม่ 50130',
      ward: 'อายุรกรรมชาย',
      bed: '3A-03',
      room: '3A',
      admitDate: '2026-03-01',
      diagnosis: 'CKD Stage 4, DM Nephropathy',
      diagnosisICD: 'N18.4, E11.2',
      attendingDoc: 'นพ.วิชัย สุขสันต์',
      admitFrom: 'OPD',
      insurance: 'บัตรทอง',
      allergies: 'Metformin (contraindicated)',
      dischargeStatus: 'planning',
      riskLevel: 'high',
      los: 3,
      expectedDischargeDate: '2026-03-06',
      bmi: 25.3,
      bloodType: 'A',
      caregiver: {
        name: 'นางจันทร์ แก้วใส',
        relation: 'ภรรยา',
        phone: '094-567-8901',
        canCare: true,
      },
      dischargePlan: {
        status: 'in_progress',
        completedItems: 3,
        totalItems: 7,
        dMethod: {
          disease: { status: 'completed', note: 'เข้าใจโรคไตเรื้อรังระยะที่ 4 และเบาหวาน' },
          medication: { status: 'completed', note: 'ยาหลายชนิด อินซูลิน, EPO, Iron' },
          environment: { status: 'completed', note: 'บ้านชั้นเดียว สะดวก' },
          treatment: { status: 'pending', note: 'เตรียมตัวสำหรับ Hemodialysis ในอนาคต, ทำ AV fistula' },
          health: { status: 'pending', note: 'สอนเรื่องอาหาร CKD, การจำกัดโปรตีน โปแตสเซียม ฟอสฟอรัส' },
          outpatient: { status: 'pending', note: 'นัด OPD ไต + OPD DM' },
          diet: { status: 'pending', note: 'จำกัดโปรตีน 0.6-0.8 g/kg/day, จำกัด K+, PO4' },
        },
        medications: [
          { name: 'Insulin Glargine', dose: '14 units', route: 'SC', frequency: 'OD', note: 'ก่อนนอน' },
          { name: 'EPO 4000 IU', dose: '1 เข็ม', route: 'SC', frequency: '2x/week', note: 'จันทร์-พฤหัสบดี' },
          { name: 'Ferrous fumarate 200mg', dose: '1 เม็ด', route: 'PO', frequency: 'OD', note: 'ก่อนอาหารเช้า' },
          { name: 'Calcium carbonate 1500mg', dose: '1 เม็ด', route: 'PO', frequency: 'TID', note: 'พร้อมอาหาร (phosphate binder)' },
          { name: 'Sodium bicarbonate 300mg', dose: '2 เม็ด', route: 'PO', frequency: 'TID', note: 'หลังอาหาร' },
          { name: 'Amlodipine 10mg', dose: '1 เม็ด', route: 'PO', frequency: 'OD', note: 'เช้า' },
        ],
        equipment: ['ชุดตรวจน้ำตาลในเลือด', 'เข็มฉีดอินซูลิน', 'เครื่องวัดความดัน'],
        specialInstructions: [
          'จำกัดอาหารโปรตีนสูง ผลไม้โปแตสเซียมสูง (กล้วย ส้ม มะละกอ)',
          'จำกัดน้ำตามที่แพทย์กำหนด',
          'วัด BS ก่อนอาหารเช้า, วัด BP เช้า-เย็น',
          'สังเกตปัสสาวะ - สี ปริมาณ ถ้าลดลงมากให้มาพบแพทย์',
          'ห้ามซื้อยาหรือสมุนไพรรับประทานเอง อาจทำลายไต',
          'เตรียมตัวทำเส้นเลือดสำหรับฟอกไต (AV fistula)',
        ],
      },
    },
  ],

  // ==================== DISCHARGED PATIENTS (FOR FOLLOW-UP) ====================
  dischargedPatients: [
    {
      id: 'D001',
      hn: '63-004321',
      an: '67-001200',
      name: 'นายทองดี เจริญผล',
      gender: 'male',
      age: 55,
      phone: '081-111-2222',
      address: '99 หมู่ 7 ต.สันกำแพง อ.สันกำแพง จ.เชียงใหม่ 50130',
      diagnosis: 'Acute MI - Post PCI',
      dischargeDate: '2026-03-02',
      ward: 'CCU',
      attendingDoc: 'นพ.สมบูรณ์ เวชการ',
      riskLevel: 'high',
      insurance: 'ข้าราชการ',
      caregiver: { name: 'นางทองสุข เจริญผล', relation: 'ภรรยา', phone: '081-222-3333' },
      followUpStatus: 'on_track',
      nextFollowUp: { date: '2026-03-04', type: 'phone_48hr', assignee: 'พว.สุดา ใจงาม' },
      followUpSchedule: [
        { date: '2026-03-04', type: 'phone_48hr', status: 'scheduled', assignee: 'พว.สุดา ใจงาม' },
        { date: '2026-03-09', type: 'phone_7day', status: 'scheduled', assignee: 'พว.สุดา ใจงาม' },
        { date: '2026-03-16', type: 'phone_14day', status: 'scheduled', assignee: 'พว.มาลี ดอกไม้' },
        { date: '2026-03-30', type: 'home_visit', status: 'scheduled', assignee: 'พว.มาลี ดอกไม้' },
        { date: '2026-04-02', type: 'opd_visit', status: 'scheduled', assignee: 'นพ.สมบูรณ์ เวชการ' },
      ],
      followUpRecords: [],
      nextOPD: '2026-04-02',
      readmitted: false,
    },
    {
      id: 'D002',
      hn: '64-007654',
      an: '67-001180',
      name: 'นางสาวอรุณี แสงจันทร์',
      gender: 'female',
      age: 62,
      phone: '082-333-4444',
      address: '67 หมู่ 5 ต.แช่ช้าง อ.สันกำแพง จ.เชียงใหม่ 50130',
      diagnosis: 'Ischemic Stroke - Rt hemiparesis',
      dischargeDate: '2026-02-20',
      ward: 'อายุรกรรมหญิง',
      attendingDoc: 'นพ.สมบูรณ์ เวชการ',
      riskLevel: 'high',
      insurance: 'บัตรทอง',
      caregiver: { name: 'นายสมศักดิ์ แสงจันทร์', relation: 'สามี', phone: '082-444-5555' },
      followUpStatus: 'on_track',
      nextFollowUp: { date: '2026-03-06', type: 'home_visit', assignee: 'พว.มาลี ดอกไม้' },
      followUpSchedule: [
        { date: '2026-02-22', type: 'phone_48hr', status: 'completed', assignee: 'พว.สุดา ใจงาม' },
        { date: '2026-02-27', type: 'phone_7day', status: 'completed', assignee: 'พว.สุดา ใจงาม' },
        { date: '2026-03-06', type: 'home_visit', status: 'scheduled', assignee: 'พว.มาลี ดอกไม้' },
        { date: '2026-03-20', type: 'phone_30day', status: 'scheduled', assignee: 'พว.มาลี ดอกไม้' },
        { date: '2026-03-20', type: 'opd_visit', status: 'scheduled', assignee: 'นพ.สมบูรณ์ เวชการ' },
      ],
      followUpRecords: [
        {
          id: 'FR001',
          date: '2026-02-22',
          type: 'phone_48hr',
          recorder: 'พว.สุดา ใจงาม',
          channel: 'โทรศัพท์',
          duration: '15 นาที',
          vitalSigns: { bp: '140/85', temp: '36.8', hr: '78' },
          assessment: {
            generalCondition: 'ดี',
            painLevel: 2,
            medication: 'รับประทานยาครบตามสั่ง',
            wound: 'ไม่มีแผล',
            movement: 'เดินด้วย Walker ได้ ยังอ่อนแรงข้างขวา',
            eating: 'ทานอาหารได้ กลืนลำบากเล็กน้อย',
            sleeping: 'นอนหลับดี',
            mentalHealth: 'วิตกกังวลเรื่องการกลับไปทำงาน',
          },
          problems: ['กลืนลำบากเล็กน้อย อาหารแข็งยังทานลำบาก', 'วิตกกังวลเรื่องการฟื้นฟู'],
          actions: ['แนะนำทานอาหารอ่อน ค่อยๆ ปรับ', 'ให้กำลังใจ อธิบายแผนฟื้นฟู', 'นัดทำกายภาพบำบัดต่อเนื่อง'],
          nextPlan: 'โทรติดตาม 7 วัน',
          overallStatus: 'stable',
        },
        {
          id: 'FR002',
          date: '2026-02-27',
          type: 'phone_7day',
          recorder: 'พว.สุดา ใจงาม',
          channel: 'โทรศัพท์',
          duration: '12 นาที',
          vitalSigns: { bp: '135/80', temp: '36.5', hr: '75' },
          assessment: {
            generalCondition: 'ดีขึ้น',
            painLevel: 1,
            medication: 'รับประทานยาครบตามสั่ง',
            wound: 'ไม่มีแผล',
            movement: 'แขน-ขาขวาแรงขึ้น ทำกายภาพสม่ำเสมอ',
            eating: 'ทานได้ดีขึ้น กลืนดีขึ้น',
            sleeping: 'นอนหลับดี',
            mentalHealth: 'ดีขึ้น มีกำลังใจ',
          },
          problems: ['ยังต้องใช้ Walker เดิน'],
          actions: ['ชมเชยที่ทำกายภาพสม่ำเสมอ', 'แนะนำออกกำลังกายเพิ่มขึ้น', 'นัดเยี่ยมบ้าน'],
          nextPlan: 'เยี่ยมบ้าน 6 มี.ค.',
          overallStatus: 'improving',
        },
      ],
      nextOPD: '2026-03-20',
      readmitted: false,
    },
    {
      id: 'D003',
      hn: '62-008765',
      an: '67-001170',
      name: 'นายประสิทธิ์ ทองคำ',
      gender: 'male',
      age: 68,
      phone: '083-555-6666',
      address: '120 หมู่ 3 ต.สันกำแพง อ.สันกำแพง จ.เชียงใหม่ 50130',
      diagnosis: 'COPD Exacerbation',
      dischargeDate: '2026-02-15',
      ward: 'อายุรกรรมชาย',
      attendingDoc: 'นพ.วิชัย สุขสันต์',
      riskLevel: 'medium',
      insurance: 'บัตรทอง',
      caregiver: { name: 'นางสมพร ทองคำ', relation: 'ภรรยา', phone: '083-666-7777' },
      followUpStatus: 'on_track',
      nextFollowUp: { date: '2026-03-15', type: 'phone_30day', assignee: 'พว.มาลี ดอกไม้' },
      followUpSchedule: [
        { date: '2026-02-17', type: 'phone_48hr', status: 'completed', assignee: 'พว.สุดา ใจงาม' },
        { date: '2026-02-22', type: 'phone_7day', status: 'completed', assignee: 'พว.สุดา ใจงาม' },
        { date: '2026-03-01', type: 'phone_14day', status: 'completed', assignee: 'พว.มาลี ดอกไม้' },
        { date: '2026-03-15', type: 'phone_30day', status: 'scheduled', assignee: 'พว.มาลี ดอกไม้' },
        { date: '2026-03-15', type: 'opd_visit', status: 'scheduled', assignee: 'นพ.วิชัย สุขสันต์' },
      ],
      followUpRecords: [
        {
          id: 'FR003',
          date: '2026-02-17',
          type: 'phone_48hr',
          recorder: 'พว.สุดา ใจงาม',
          channel: 'โทรศัพท์',
          duration: '10 นาที',
          vitalSigns: { bp: '130/80', temp: '36.5', hr: '82' },
          assessment: {
            generalCondition: 'ดี',
            painLevel: 0,
            medication: 'ใช้ยาพ่นถูกต้อง',
            wound: 'ไม่มี',
            movement: 'เดินได้ เหนื่อยเร็ว',
            eating: 'ทานได้ปกติ',
            sleeping: 'นอนหลับดี หนุนหมอนสูง',
            mentalHealth: 'ปกติ',
          },
          problems: ['เหนื่อยง่ายเวลาเดินไกล'],
          actions: ['แนะนำทำ Breathing exercise', 'หลีกเลี่ยงฝุ่นควัน'],
          nextPlan: 'โทรติดตาม 7 วัน',
          overallStatus: 'stable',
        },
        {
          id: 'FR004',
          date: '2026-02-22',
          type: 'phone_7day',
          recorder: 'พว.สุดา ใจงาม',
          channel: 'โทรศัพท์',
          duration: '8 นาที',
          vitalSigns: { bp: '128/78', temp: '36.4', hr: '80' },
          assessment: {
            generalCondition: 'ดีขึ้น',
            painLevel: 0,
            medication: 'ใช้ยาพ่นถูกต้อง',
            wound: 'ไม่มี',
            movement: 'เดินได้ดีขึ้น',
            eating: 'ทานได้ดี',
            sleeping: 'หลับดี',
            mentalHealth: 'ปกติ',
          },
          problems: [],
          actions: ['ชมเชยที่ดูแลตนเองดี', 'เน้นย้ำงดสูบบุหรี่'],
          nextPlan: 'โทรติดตาม 14 วัน',
          overallStatus: 'improving',
        },
        {
          id: 'FR005',
          date: '2026-03-01',
          type: 'phone_14day',
          recorder: 'พว.มาลี ดอกไม้',
          channel: 'โทรศัพท์',
          duration: '10 นาที',
          vitalSigns: { bp: '125/75', temp: '36.5', hr: '78' },
          assessment: {
            generalCondition: 'ดี',
            painLevel: 0,
            medication: 'ใช้ยาพ่นสม่ำเสมอ',
            wound: 'ไม่มี',
            movement: 'เดินได้ดี ออกกำลังกายเบาๆ ได้',
            eating: 'ทานได้ดี น้ำหนักเพิ่ม 1 กก.',
            sleeping: 'หลับดี',
            mentalHealth: 'ดี มีกำลังใจ',
          },
          problems: [],
          actions: ['ให้กำลังใจ', 'นัดโทรติดตาม 30 วัน และพบแพทย์'],
          nextPlan: 'โทรติดตาม 30 วัน + นัดพบแพทย์',
          overallStatus: 'improving',
        },
      ],
      nextOPD: '2026-03-15',
      readmitted: false,
    },
    {
      id: 'D004',
      hn: '65-002345',
      an: '67-001185',
      name: 'นางแก้ว สุวรรณ',
      gender: 'female',
      age: 75,
      phone: '084-777-8888',
      address: '42 หมู่ 6 ต.ออนใต้ อ.สันกำแพง จ.เชียงใหม่ 50130',
      diagnosis: 'DM with Hypoglycemia, CKD stage 3',
      dischargeDate: '2026-02-18',
      ward: 'อายุรกรรมหญิง',
      attendingDoc: 'นพ.วิชัย สุขสันต์',
      riskLevel: 'high',
      insurance: 'บัตรทอง',
      caregiver: { name: 'นางสาวจันทร์ สุวรรณ', relation: 'หลานสาว', phone: '084-888-9999' },
      followUpStatus: 'overdue',
      nextFollowUp: { date: '2026-03-02', type: 'phone_14day', assignee: 'พว.สุดา ใจงาม' },
      followUpSchedule: [
        { date: '2026-02-20', type: 'phone_48hr', status: 'completed', assignee: 'พว.สุดา ใจงาม' },
        { date: '2026-02-25', type: 'phone_7day', status: 'completed', assignee: 'พว.สุดา ใจงาม' },
        { date: '2026-03-02', type: 'phone_14day', status: 'overdue', assignee: 'พว.สุดา ใจงาม' },
        { date: '2026-03-18', type: 'home_visit', status: 'scheduled', assignee: 'พว.มาลี ดอกไม้' },
        { date: '2026-03-18', type: 'opd_visit', status: 'scheduled', assignee: 'นพ.วิชัย สุขสันต์' },
      ],
      followUpRecords: [
        {
          id: 'FR006',
          date: '2026-02-20',
          type: 'phone_48hr',
          recorder: 'พว.สุดา ใจงาม',
          channel: 'โทรศัพท์',
          duration: '20 นาที',
          vitalSigns: { bp: '140/85', temp: '36.7', hr: '80' },
          assessment: {
            generalCondition: 'พอใช้',
            painLevel: 0,
            medication: 'สับสนเรื่องเวลาฉีดอินซูลิน',
            wound: 'ไม่มี',
            movement: 'เดินได้',
            eating: 'ทานน้อย กลัวน้ำตาลขึ้น',
            sleeping: 'นอนไม่ค่อยหลับ กังวล',
            mentalHealth: 'วิตกกังวล',
          },
          problems: ['สับสนเรื่องยาอินซูลิน', 'ทานอาหารน้อยเกินไป เสี่ยง Hypoglycemia', 'หลานสาวทำงานกลางวัน ไม่มีคนดูแล'],
          actions: ['สอนซ้ำเรื่องอินซูลิน ส่งรูปตาราง LINE', 'แนะนำอาหารที่เหมาะสม', 'ประสานงาน อสม. ติดตามช่วงกลางวัน'],
          nextPlan: 'โทรติดตาม 7 วัน',
          overallStatus: 'concern',
        },
        {
          id: 'FR007',
          date: '2026-02-25',
          type: 'phone_7day',
          recorder: 'พว.สุดา ใจงาม',
          channel: 'โทรศัพท์ + LINE VDO Call',
          duration: '25 นาที',
          vitalSigns: { bp: '138/82', temp: '36.5', hr: '78' },
          assessment: {
            generalCondition: 'ดีขึ้น',
            painLevel: 0,
            medication: 'ฉีดอินซูลินถูกเวลาแล้ว (ดูตาราง)',
            wound: 'ไม่มี',
            movement: 'เดินได้',
            eating: 'ทานได้ดีขึ้น แบ่งมื้อย่อย',
            sleeping: 'หลับดีขึ้น',
            mentalHealth: 'ดีขึ้น มี อสม. มาเยี่ยม',
          },
          problems: ['BS ยังแกว่ง 80-250 mg/dL'],
          actions: ['รายงานค่า BS แพทย์', 'แพทย์ปรับขนาดอินซูลิน', 'นัดโทรติดตาม 14 วัน'],
          nextPlan: 'โทรติดตาม 14 วัน',
          overallStatus: 'stable',
        },
      ],
      nextOPD: '2026-03-18',
      readmitted: false,
    },
    {
      id: 'D005',
      hn: '66-003210',
      an: '67-001190',
      name: 'นายวิชัย มั่นคง',
      gender: 'male',
      age: 50,
      phone: '085-999-0000',
      address: '88 หมู่ 2 ต.บวกค้าง อ.สันกำแพง จ.เชียงใหม่ 50130',
      diagnosis: 'Appendicitis - Post Appendectomy',
      dischargeDate: '2026-03-04',
      ward: 'ศัลยกรรม',
      attendingDoc: 'นพ.ศักดิ์ชัย ผ่าตัดเก่ง',
      riskLevel: 'low',
      insurance: 'ประกันสังคม',
      caregiver: { name: 'นางวรรณา มั่นคง', relation: 'ภรรยา', phone: '086-000-1111' },
      followUpStatus: 'new',
      nextFollowUp: { date: '2026-03-06', type: 'phone_48hr', assignee: 'พว.สุดา ใจงาม' },
      followUpSchedule: [
        { date: '2026-03-06', type: 'phone_48hr', status: 'scheduled', assignee: 'พว.สุดา ใจงาม' },
        { date: '2026-03-11', type: 'opd_visit', status: 'scheduled', assignee: 'นพ.ศักดิ์ชัย ผ่าตัดเก่ง' },
      ],
      followUpRecords: [],
      nextOPD: '2026-03-11',
      readmitted: false,
    },
    {
      id: 'D006',
      hn: '63-005678',
      an: '67-001150',
      name: 'นางมาลี ดอกจันทร์',
      gender: 'female',
      age: 45,
      phone: '086-111-2222',
      address: '34 หมู่ 1 ต.สันกำแพง อ.สันกำแพง จ.เชียงใหม่ 50130',
      diagnosis: 'Pneumonia with Sepsis',
      dischargeDate: '2026-02-10',
      ward: 'อายุรกรรมหญิง',
      attendingDoc: 'นพ.สมบูรณ์ เวชการ',
      riskLevel: 'medium',
      insurance: 'บัตรทอง',
      caregiver: { name: 'นายสมชาย ดอกจันทร์', relation: 'สามี', phone: '086-222-3333' },
      followUpStatus: 'completed',
      nextFollowUp: null,
      followUpSchedule: [
        { date: '2026-02-12', type: 'phone_48hr', status: 'completed', assignee: 'พว.สุดา ใจงาม' },
        { date: '2026-02-17', type: 'phone_7day', status: 'completed', assignee: 'พว.สุดา ใจงาม' },
        { date: '2026-02-24', type: 'phone_14day', status: 'completed', assignee: 'พว.มาลี ดอกไม้' },
        { date: '2026-03-10', type: 'opd_visit', status: 'completed', assignee: 'นพ.สมบูรณ์ เวชการ' },
      ],
      followUpRecords: [
        {
          id: 'FR008',
          date: '2026-02-12',
          type: 'phone_48hr',
          recorder: 'พว.สุดา ใจงาม',
          channel: 'โทรศัพท์',
          duration: '10 นาที',
          vitalSigns: { bp: '120/75', temp: '37.0', hr: '82' },
          assessment: { generalCondition: 'ดี', painLevel: 1, medication: 'รับประทานยาครบ', wound: 'ไม่มี', movement: 'เดินได้ เหนื่อยเร็ว', eating: 'ทานได้', sleeping: 'หลับได้', mentalHealth: 'ปกติ' },
          problems: ['เหนื่อยเร็ว ยังไม่มีแรง'],
          actions: ['แนะนำพักผ่อน ค่อยๆ เพิ่มกิจกรรม'],
          nextPlan: 'โทรติดตาม 7 วัน',
          overallStatus: 'stable',
        },
        {
          id: 'FR009',
          date: '2026-02-17',
          type: 'phone_7day',
          recorder: 'พว.สุดา ใจงาม',
          channel: 'โทรศัพท์',
          duration: '8 นาที',
          vitalSigns: { bp: '118/72', temp: '36.5', hr: '78' },
          assessment: { generalCondition: 'ดีขึ้นมาก', painLevel: 0, medication: 'รับประทานยาครบ', wound: 'ไม่มี', movement: 'กลับมาทำงานบ้านได้', eating: 'ทานได้ดี', sleeping: 'หลับดี', mentalHealth: 'ดี' },
          problems: [],
          actions: ['ชมเชย'],
          nextPlan: 'โทรติดตาม 14 วัน',
          overallStatus: 'improving',
        },
        {
          id: 'FR010',
          date: '2026-02-24',
          type: 'phone_14day',
          recorder: 'พว.มาลี ดอกไม้',
          channel: 'โทรศัพท์',
          duration: '5 นาที',
          vitalSigns: { bp: '115/70', temp: '36.4', hr: '75' },
          assessment: { generalCondition: 'ดี กลับมาปกติ', painLevel: 0, medication: 'ยาหมดแล้ว', wound: 'ไม่มี', movement: 'ปกติ', eating: 'ปกติ', sleeping: 'ปกติ', mentalHealth: 'ดี' },
          problems: [],
          actions: ['ปิดเคส follow-up', 'นัดพบแพทย์ตามนัด'],
          nextPlan: 'พบแพทย์ตามนัด 10 มี.ค.',
          overallStatus: 'recovered',
        },
      ],
      nextOPD: '2026-03-10',
      readmitted: false,
    },
  ],

  // ==================== HOME VISIT DATA ====================
  homeVisits: [
    {
      id: 'HV001',
      patientId: 'D002',
      patientName: 'นางสาวอรุณี แสงจันทร์',
      hn: '64-007654',
      date: '2026-03-06',
      time: '09:00',
      status: 'scheduled',
      team: ['พว.มาลี ดอกไม้', 'นักกายภาพบำบัด สมศรี'],
      address: '67 หมู่ 5 ต.แช่ช้าง อ.สันกำแพง จ.เชียงใหม่ 50130',
      objectives: ['ประเมินสภาพบ้าน ความปลอดภัย', 'ประเมิน ADL และการฟื้นฟู', 'ประเมินผู้ดูแล', 'ปรับแผนกายภาพบำบัดที่บ้าน'],
      diagnosis: 'Ischemic Stroke - Rt hemiparesis',
      visitRecord: null,
    },
    {
      id: 'HV002',
      patientId: 'D004',
      patientName: 'นางแก้ว สุวรรณ',
      hn: '65-002345',
      date: '2026-03-18',
      time: '10:00',
      status: 'scheduled',
      team: ['พว.มาลี ดอกไม้'],
      address: '42 หมู่ 6 ต.ออนใต้ อ.สันกำแพง จ.เชียงใหม่ 50130',
      objectives: ['ประเมินการใช้ยาอินซูลิน', 'ตรวจ BS', 'ประเมินอาหารที่รับประทาน', 'พบ อสม. ในพื้นที่'],
      diagnosis: 'DM with Hypoglycemia, CKD stage 3',
      visitRecord: null,
    },
    {
      id: 'HV003',
      patientId: 'D001',
      patientName: 'นายทองดี เจริญผล',
      hn: '63-004321',
      date: '2026-03-30',
      time: '09:30',
      status: 'scheduled',
      team: ['พว.มาลี ดอกไม้', 'พว.สุดา ใจงาม'],
      address: '99 หมู่ 7 ต.สันกำแพง อ.สันกำแพง จ.เชียงใหม่ 50130',
      objectives: ['ประเมินการฟื้นตัวหลังทำ PCI', 'วัด BP, HR', 'ประเมินการออกกำลังกาย', 'ประเมินสภาพจิตใจ'],
      diagnosis: 'Acute MI - Post PCI',
      visitRecord: null,
    },
  ],

  // ==================== STAFF ====================
  staff: [
    { id: 'S001', name: 'พว.สุดา ใจงาม', role: 'พยาบาลวิชาชีพ', department: 'Discharge Center', phone: '053-331-234 ต่อ 101' },
    { id: 'S002', name: 'พว.มาลี ดอกไม้', role: 'พยาบาลวิชาชีพ', department: 'Discharge Center', phone: '053-331-234 ต่อ 102' },
    { id: 'S003', name: 'พว.จันทร์ สว่าง', role: 'พยาบาลวิชาชีพ', department: 'Discharge Center', phone: '053-331-234 ต่อ 103' },
    { id: 'S004', name: 'นพ.วิชัย สุขสันต์', role: 'แพทย์', department: 'อายุรกรรม', phone: '053-331-234 ต่อ 201' },
    { id: 'S005', name: 'นพ.สมบูรณ์ เวชการ', role: 'แพทย์', department: 'อายุรกรรม', phone: '053-331-234 ต่อ 202' },
    { id: 'S006', name: 'นพ.ศักดิ์ชัย ผ่าตัดเก่ง', role: 'แพทย์', department: 'ศัลยกรรม', phone: '053-331-234 ต่อ 301' },
    { id: 'S007', name: 'พญ.นิภา เด็กดี', role: 'แพทย์', department: 'กุมารเวชกรรม', phone: '053-331-234 ต่อ 401' },
  ],

  // ==================== OPD MOCKUP ====================
  opd: {
    todayPatients: 125,
    waitingQueue: 18,
    completed: 95,
    avgWaitTime: '35 นาที',
    clinics: [
      { name: 'คลินิกอายุรกรรม', patients: 35, waiting: 5, doctor: 'นพ.วิชัย สุขสันต์' },
      { name: 'คลินิกศัลยกรรม', patients: 20, waiting: 3, doctor: 'นพ.ศักดิ์ชัย ผ่าตัดเก่ง' },
      { name: 'คลินิกกุมารเวชกรรม', patients: 15, waiting: 2, doctor: 'พญ.นิภา เด็กดี' },
      { name: 'คลินิกสูติ-นรีเวช', patients: 12, waiting: 2, doctor: 'พญ.อรุณ สายน้ำ' },
      { name: 'คลินิกทั่วไป', patients: 43, waiting: 6, doctor: 'นพ.ธนกร แพทย์ดี' },
    ],
  },

  // ==================== ER MOCKUP ====================
  er: {
    currentPatients: 8,
    criticalLevel: { resuscitation: 0, emergency: 1, urgent: 3, lessUrgent: 2, nonUrgent: 2 },
    avgWaitTime: '12 นาที',
    todayTotal: 32,
    admitted: 5,
    patients: [
      { name: 'นายสมพงษ์ ดีงาม', age: 45, triage: 'emergency', chief: 'เจ็บหน้าอกรุนแรง 1 ชม.', time: '09:30', status: 'กำลังรักษา' },
      { name: 'นางสาวนิดา สมใจ', age: 30, triage: 'urgent', chief: 'ปวดท้องรุนแรง', time: '09:45', status: 'รอผลตรวจ' },
      { name: 'เด็กชายเก่ง ดีมาก', age: 8, triage: 'urgent', chief: 'ไข้สูง ชัก 1 ครั้ง', time: '10:00', status: 'กำลังรักษา' },
      { name: 'นายสุเทพ ขยัน', age: 55, triage: 'urgent', chief: 'หายใจลำบาก', time: '10:15', status: 'รอพบแพทย์' },
      { name: 'นางวัน ใจเย็น', age: 65, triage: 'lessUrgent', chief: 'วิงเวียนศีรษะ 2 วัน', time: '10:30', status: 'รอพบแพทย์' },
    ],
  },

  // ==================== WARD MANAGEMENT MOCKUP ====================
  wardManagement: {
    wards: [
      { name: 'อายุรกรรมชาย (3A)', beds: 12, occupied: 10, available: 2, nurses: 4, patients: ['นายสมชาย ใจดี', 'นายประเสริฐ มั่นคง', 'นายสุรชัย แก้วใส'] },
      { name: 'อายุรกรรมหญิง (2B)', beds: 12, occupied: 9, available: 3, nurses: 4, patients: ['นางสมหญิง รักสุข', 'นางวิไล ชูศรี'] },
      { name: 'ศัลยกรรม (4)', beds: 10, occupied: 8, available: 2, nurses: 3, patients: ['นายอำนวย พรมดี', 'นางบุญมี ศรีสุข'] },
      { name: 'กุมารเวชกรรม (5)', beds: 8, occupied: 7, available: 1, nurses: 3, patients: ['เด็กชายภูมิ สดใส'] },
      { name: 'สูติ-นรีเวช (6)', beds: 8, occupied: 6, available: 2, nurses: 3, patients: [] },
      { name: 'CCU/ICU', beds: 6, occupied: 5, available: 1, nurses: 6, patients: [] },
      { name: 'ห้องพิเศษ', beds: 4, occupied: 2, available: 2, nurses: 2, patients: [] },
    ],
    totalBeds: 60,
    totalOccupied: 47,
    totalAvailable: 13,
    occupancyRate: 78.3,
  },

  // ==================== NOTIFICATIONS ====================
  notifications: [
    { id: 'N001', type: 'urgent', title: 'ติดตามผลเลยกำหนด', message: 'นางแก้ว สุวรรณ - โทรติดตาม 14 วัน เลยกำหนด 2 วัน', time: '2 วันที่แล้ว', read: false },
    { id: 'N002', type: 'warning', title: 'จำหน่ายวันนี้', message: '3 ผู้ป่วยพร้อมจำหน่ายวันนี้: นายประเสริฐ, นางวิไล, นายอำนวย', time: '08:00', read: false },
    { id: 'N003', type: 'info', title: 'เยี่ยมบ้านพรุ่งนี้', message: 'เยี่ยมบ้าน นางสาวอรุณี แสงจันทร์ เวลา 09:00 น.', time: '14:00', read: true },
    { id: 'N004', type: 'info', title: 'ผู้ป่วยใหม่', message: 'นายประสิทธิ์ ลือชา รับเข้า Ward อายุรกรรมชาย', time: '08:00', read: true },
    { id: 'N005', type: 'success', title: 'Follow-up สำเร็จ', message: 'ปิดเคส นางมาลี ดอกจันทร์ - ฟื้นตัวดี', time: 'เมื่อวาน', read: true },
  ],
};

// Helper functions
function formatThaiDate(dateStr) {
  if (!dateStr) return '-';
  const months = ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'];
  const d = new Date(dateStr);
  return `${d.getDate()} ${months[d.getMonth()]} ${d.getFullYear() + 543}`;
}

function formatThaiDateFull(dateStr) {
  if (!dateStr) return '-';
  const days = ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'];
  const months = ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'];
  const d = new Date(dateStr);
  return `วัน${days[d.getDay()]}ที่ ${d.getDate()} ${months[d.getMonth()]} พ.ศ. ${d.getFullYear() + 543}`;
}

function getFollowUpTypeName(type) {
  const types = {
    phone_48hr: 'โทรติดตาม 48 ชม.',
    phone_7day: 'โทรติดตาม 7 วัน',
    phone_14day: 'โทรติดตาม 14 วัน',
    phone_30day: 'โทรติดตาม 30 วัน',
    home_visit: 'เยี่ยมบ้าน',
    opd_visit: 'นัดพบแพทย์ OPD',
  };
  return types[type] || type;
}

function getStatusBadge(status) {
  const badges = {
    planning: { text: 'กำลังวางแผน', class: 'badge-warning' },
    ready: { text: 'พร้อมจำหน่าย', class: 'badge-success' },
    discharged: { text: 'จำหน่ายแล้ว', class: 'badge-info' },
    scheduled: { text: 'ตามกำหนด', class: 'badge-info' },
    completed: { text: 'เสร็จสิ้น', class: 'badge-success' },
    overdue: { text: 'เลยกำหนด', class: 'badge-danger' },
    on_track: { text: 'ตามแผน', class: 'badge-success' },
    new: { text: 'ใหม่', class: 'badge-primary' },
    in_progress: { text: 'กำลังดำเนินการ', class: 'badge-warning' },
  };
  return badges[status] || { text: status, class: 'badge-secondary' };
}

function getRiskBadge(level) {
  const badges = {
    low: { text: 'ความเสี่ยงต่ำ', class: 'badge-success' },
    medium: { text: 'ความเสี่ยงปานกลาง', class: 'badge-warning' },
    high: { text: 'ความเสี่ยงสูง', class: 'badge-danger' },
  };
  return badges[level] || { text: level, class: 'badge-secondary' };
}

function getOverallStatusText(status) {
  const statuses = {
    stable: 'คงที่',
    improving: 'ดีขึ้น',
    concern: 'ต้องเฝ้าระวัง',
    worsening: 'แย่ลง',
    recovered: 'ฟื้นตัวดี',
  };
  return statuses[status] || status;
}

function daysFromNow(dateStr) {
  const now = new Date('2026-03-04');
  const d = new Date(dateStr);
  const diff = Math.ceil((d - now) / (1000 * 60 * 60 * 24));
  return diff;
}
